#!/usr/bin/env python3
"""Calculate factors of composite numbers using Pollard's Rho algorithm."""

import sys

from pollard_rho import pollard_rho, pollard_brent_rho


def main(file_path: str) -> None:
    """Reads numbers from a file and factors them."""
    with open(file_path) as f:
        for line in f:
            num = int(line)
            factor = pollard_brent_rho(num)
            print(f"{num}={num // factor}*{factor}", flush=True)


if __name__ == "__main__":
    main(sys.argv[1])
