#!/usr/bin/env python3
"""Calculate prime factors of a composite using Pollard's Rho algorithm."""

import sys

from pollard_rho import pollard_rho


def main(file_path: str) -> None:
    """Reads a number from a file and factors it."""
    with open(file_path) as f:
        num = int(f.readline())
        factor = pollard_rho(num)

    print(f"{num}={num // factor}*{factor}")


if __name__ == "__main__":
    main(sys.argv[1])
